django_lec/django_lec/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello/", include("hello.urls")),  # here we are saying the default page for hello app is http://127.0.0.1:8000/hello
    path("newyear/", include("newyear.urls")), # here we are saying the default page for newyear app is http://127.0.0.1:8000/newyear
    path("tasks/", include("tasks.urls"))  # here we are saying the default page for tasks app is http://127.0.0.1:8000/tasks
]

django_lec/hello/urls.py
from django.urls import path

from . import views # the dot means current folder


#  "" default basically signiviews the app name http://127.0.0.1:8000/hello thats why we did empty string
""" our default page is http://127.0.0.1:8000/hello
    now if we want to add another page that says hello selam we do path( "selam", the the view function)
"""
# <str:name> bsically means "wheni have a string variable name"

urlpatterns = [
    
    path("", views.hello_world),
    path("selam", views.selam, name = "selam"),
    path("<str:name>", views.greet, name = "greet")  
]

django_lec/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index" )
]

django_lec/tasks/urls.py
from django.urls import path

from .import views

# this will avoid conflict if we have the same functions name in different apps.
app_name = "tasks" 

urlpatterns = [

    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

django_lec/hello/models.py
from django.db import models

# Create your models here.

django_lec/newyear/models.py
from django.db import models

# Create your models here.

django_lec/tasks/models.py
from django.db import models
# Create your models here.

django_lec/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

# This function handles only the logice, the html design is inside html file good design!
def hello_world(request):
    return render (request, "hello/hello_world.html" ) 

# this function handels both logic and html together, for a bigger and organized project its considered a bad design
def selam(request):
    return HttpResponse("Hello Selam!" )  # return hello Selam

# This function handles only the logice, the html design is inside html file good design!
def greet(request, name):
    # the thirs parameter is a dictionary 
    return render(request, "hello/greet.html", {
    "name": "name".capitalize()
    })

django_lec/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.

def index(request):
    now = datetime.datetime.now()

    # here we have a newyear string varibale mapped to now.day == 1 and now.month == 1, inside the index.html we will check
    # if year newyear True or False when index return the render function.
    
    return render(request, "newyear/index.html", {
         "newyear" : now.day == 1 and now.month == 1
        }
    )

django_lec/tasks/views.py
from django import forms # this will allow us to create forms
from django.http import HttpResponseRedirect # this will allow us to redirect the user to another page
from django.shortcuts import render # this will allow us to render the html file
from django.urls import reverse # this will allow us to get the url pattern for the index page


# Create your views here.

 

# tasks = [] # this is a list of tasks, if session exit we dont need this

class NewTaskForm(forms.Form): # this will allow us to create a form

    # create a form that will be used in the add.html file

    # label is the name of the field that will be displayed in the html file

    task = forms.CharField(label="New Task") # this is the label that will be displayed in the html file

    # priority = forms.IntegerField(label="Priority", min_value=1, max_value=3) # this is the label that will be displayed in the html file



def index(request):
    if "tasks" not in request.session: # if the tasks key is not in the sessions dictionary then we will add it
        request.session["tasks"] = []

    # when we create the mapping "tasks":tasks the one inside the "" is used in the html file and the one after the : is the one we are passing in from here
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]  # this is the list of tasks we created above                                             
    })

def add(request):

    # if the action of the form is POST then we will create a new form with the data that was submitted

    if request.method == 'POST': # when submitting a form the method is always POST
         
        # requet.post is the data that was submitted
        form = NewTaskForm(request.POST)

        if form.is_valid():

            # if the form is valid then we will get the data from the form and add it to the tasks list
            # form.cleaned_data  will give access to all the data that was submitted
            # we need the task key because that is the name of the field in the form

            task = form.cleaned_data["task"]

            # add the task to the tasks list
            request.session["tasks"] += [task] # this is the same as tasks.append(task) but we are using 
                                        # sessions to store the data so people can see different tasks per session

            # if we don't have the code below we have to manually go to the index page to see the new task added
            # but with the code below we will be redirected to the index page and we will see the new task added

            # reverse is a built in function that will return the url pattern for the index page   
            return HttpResponseRedirect(reverse("tasks:index"))
        
        else:   
            # else if  the form is not valid then we will render the add.html page again with the form
            return render(request, "tasks/add.html", {
                "form": form
            })

            
    # else if the action of the form is GET then we will render the add.html page with the form
    return render(request, "tasks/add.html", {
       "form": NewTaskForm() # this is the form we created above
    })

django_lec/hello/templates/hello/greet.html
<!DOCTYPE>
<html lang="en">
    <Head> 
        <title> greet </title>
    </Head>

    <body>
        <!-- the two currly braces are the way to insert python variables from views-->
        <h1> Hello, {{name}}! </h1>
    </body>
</html>

django_lec/hello/templates/hello/hello_world.html
<!DOCTYPE>
<html lang="en">
    <Head> 
        <title> hello </title>
    </Head>

    <body>
        <h1> Hello Word! </h1>
    </body>
</html>

django_lec/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang ="en">
    <head>
        <title>Is it Newyear ? </title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>

    <body>
         <!-- if a new year say YES else say NO-->  
        <!-- since html does allow logica statment we use Djano to insert logical statement 
            the way we do that is using    open curly bracket % <python logical statement> % closed curly bracket
            check the bottom logic to understand
        --> 
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}

    </body>

</html>

django_lec/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

<!-- inisde the block body I  would like to insert this content-->
{% block body %} 
    <h1> Add Task </h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}

        <!-- you can use django to add forms the use the farable form here, it's simpler that way -->
        {{ form }}
        <input type="submit">
    </form>

    <!-- for tasks:add to work we have to have apps_name = "tasks" inside views.py -->
    <a href=" {% url 'tasks:index' %} " > view task</a>

{% endblock %}

django_lec/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

<!-- inisde the block body I  would like to insert this content-->
{% block body %}

    <h1>Tasks</h1>

    <ul>
        {% for task in tasks %}
            <li>
                {{ task.title }}
            </li>
        <!-- if the list is empty then print say no task -->
        {% empty %}
            <li>
                No Task
            </li>
        {% endfor %}
        

    </ul>

   
    <a href="{% url 'tasks:add' %}" > Add Task </a> 

{% endblock %}

django_lec/tasks/templates/tasks/layout.html
<!DOCTYPE html>

<html>
    <head>
        <title>Tasks</title>
    </head>

    <body>
    <!-- here am saying other pages can inherit from this, and the only thing that chnge is the block body --> 
    {% block body%}
    {% endblock %}
    

    </body>

</html>